config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :favorites, only: [:create, :destroy, :index]
  resources :pets
  get '/top', to: 'pets#top'
  root 'pets#index'

  devise_for :users
  resources :users, only: [:index, :show]

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end
  
  resources :conversations do
    resources :messages
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader

  validates :image, presence: true
  validates :content, presence: true
  validates :select_animal, presence: true
  validates :age, presence: true
  validates :gender, presence: true
  validates :current_location, presence: true
  validates :prefecture, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["age", "castrated", "cat_species", "content", "created_at", "current_location", "dog_breed", "id", "image", "negotiating", "prefecture", "select_animal", "gender", "title", "updated_at", "user_id", "vaccinated"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["favorites", "user"]
  end

  scope :early_registration_date, -> {order(created_at: :asc)}
  scope :old_registration_date, -> {order(created_at: :desc)}
  scope :select_animal, -> (p_select_animal){where(select_animal: p_select_animal)}

  enum select_animal: { dog: 0, cat: 1 }
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  # before_action :set_pet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  # GET /pets or /pets.json
  def index
    # raise "エラーメッセージ"
    @pets = Pet.all
    @search = @pets.ransack(params[:q])
    @pets = @search.result
  
    case params[:sort]
    when "1"
      @pets = @pets.old_registration_date
    when "2"
      @pets = @pets.early_registration_date
    end
  end

  # GET /pets/1 or /pets/1.json
  def show
    set_pet
    @favorite = current_user.favorites.find_by(pet_id: @pet.id)
  end

  # GET /pets/new
  def new
    recruiter_check
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
    set_pet
  end

  # POST /pets or /pets.json
  def create
    @pet = current_user.pets.build(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    set_pet
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    set_pet
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def top
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:image, :title, :content, :select_animal, :age, :gender, :current_location, :prefecture, :dog_breed, :cat_species, :castrated, :vaccinated)
    end

    def recruiter_check
      if current_user.role != "recruiter"
        redirect_to pets_path
      end
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_with(model: pet) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :画像 %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :本文、詳細情報や募集要項など %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :犬もしくは猫を選択してください %>
    <%= form.select :select_animal, [["犬", "dog"], ["猫", "cat"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= form.label :年齢 %>
    <%= form.text_field :age %>
  </div>

  <div class="field">
    <%= form.label :性別 %>
    <%= form.select :gender, ["オス", "メス"],{ include_blank: "選択してください"} %>
  </div>

  <div class="field">
    <%= form.label :現在地 %>
    <%= form.text_field :current_location %>
  </div>

  <div class="field">
    <%= form.label :都道府県 %>
    <%= form.select :prefecture, ["北海道", "青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県", 
    "茨城県", "栃木県", "群馬県", "埼玉県", "千葉県", "東京都", "神奈川県", "新潟県", "富山県", "石川県", "福井県", 
    "山梨県", "長野県", "岐阜県", "静岡県", "愛知県", "三重県", "滋賀県", "京都府", "大阪府", "兵庫県", "奈良県", "和歌山県",
    "鳥取県", "島根県", "岡山県", "広島県", "山口県", "徳島県", "香川県", "愛媛県", "高知県",
    "福岡県", "佐賀県", "長崎県", "熊本県", "大分県", "宮崎県", "鹿児島県", "沖縄県"], { include_blank: "選択してください"} %>
  </div>

  <div class="field">
    <%= form.label :犬種 %>
    <%= form.text_field :dog_breed %>
  </div>

  <div class="field">
    <%= form.label :猫種 %>
    <%= form.text_field :cat_species %>
  </div>

  <div class="field">
    <%= form.label :去勢済み %>
    <%= form.check_box :castrated %>
  </div>

  <div class="field">
    <%= form.label :ワクチン接種済み %>
    <%= form.check_box :vaccinated %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>登録内容を編集する</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<h1>里親募集一覧</h1>
<p id="notice"><%= notice %></p>

<%= search_form_for @search, url: pets_path do |f| %>
  <div class="row">
    <div>
      <div>
        <%= f.select :select_animal_eq, Pet.select_animals_i18n.invert.map{|key, value| [key, Pet.select_animals[value]]}, { include_blank: "選択してください" } %>
        <%= select_tag "sort", options_for_select([['選択してください', ''], ['新しい順', 1], ['古い順', 2]]) %>
      </div>
      <div>
        <%= f.submit %>
      </div>
    </div>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th>画像</th>
      <th>紹介文など</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @pets.each do |pet| %>
      <tr>
        <td><%= image_tag pet.image.url, size:"80x80" %></td>
        <td><%= pet.content %></td>
        <% if current_user %>
          <td><%= link_to '詳細', pet %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user %>
  <% if current_user.role == "recruiter" %>
    <%= link_to '新規の募集を投稿する', new_pet_path %>
  <% end %>

  <% if current_user.role != "recruiter" %>
    <%= link_to 'お気に入り登録一覧', favorites_path %>
  <% end %>
<% end %>

<% unless current_user %>
  <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %>
  <%= link_to 'ゲスト管理者ログイン（閲覧用）', users_guest_admin_sign_in_path, method: :post %>
<% end %>

app/views/pets/new.html.erb
<h1>新規募集登録</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>画像:</strong>
  <%= image_tag @pet.image.url %>
</p>

<% if current_user.role != "recruiter" %>
  <% unless @pet.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(pet_id: @pet.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
  <% end %>
<% end %>

<% unless @pet.user_id == current_user.id %>
  <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: @pet.user.id), method: :post %>
<% end %>
<%= link_to 'TOPに戻る', pets_path %>

<% if current_user.role == "recruiter" && @pet.user_id == current_user.id %>
  <%= link_to '編集', edit_pet_path(@pet) %>
  <%= link_to '削除', @pet, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/pets/top.html.erb
<div class="cover">
</div>